-- UNIR CONSULTAS

-- MESMO NUMERO DE CAMPOS SELECIONADOS
-- TIPO DOS CAMPOS DEVE SER IGUAL

SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES; -- 12 BAIRROS

SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES; -- 4 BAIRROS

SELECT DISTINCT BAIRRO, 'CLIENTE' AS ORIGEM FROM TABELA_DE_CLIENTES
UNION ALL -- TRÁS REPETIÇÕES
SELECT DISTINCT BAIRRO, 'FORNECEDOR' AS ORIGEM FROM TABELA_DE_VENDEDORES
ORDER BY BAIRRO;
