-- VIEW: SALVAR CONSULTA NA MAMÓRIA COM UM NOME COMO TABELA VIRTUAL (EXIBIÇÕES)

-- AULA ANTERIOR 

SELECT MEDIA_EMBALAGENS.EMBALAGEM, MEDIA_EMBALAGENS.PRECO_MEDIO
FROM (
	SELECT EMBALAGEM, AVG(PRECO_DE_LISTA) AS PRECO_MEDIO 
	FROM TABELA_DE_PRODUTOS
	GROUP BY EMBALAGEM) MEDIA_EMBALAGENS
WHERE PRECO_MEDIO <= 10;

-- CRIAR VIEW COM A SUBQUERY

CREATE VIEW MEDIA_EMBALAGEM AS
SELECT EMBALAGEM, AVG(PRECO_DE_LISTA) AS PRECO_MEDIO 
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM;

SELECT * FROM MEDIA_EMBALAGEM;

-- CONSULTA ANTERIOR 

SELECT EMBALAGEM, PRECO_MEDIO
FROM MEDIA_EMBALAGEM
WHERE PRECO_MEDIO <= 10;

-- DESAFIO: REFAZER CONSULTA

SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, SUM(INF.QUANTIDADE) AS QUANTIDADE 
FROM ITENS_NOTAS_FISCAIS  INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO HAVING SUM(INF.QUANTIDADE) > 394000 
ORDER BY SUM(INF.QUANTIDADE) DESC;

CREATE VIEW VW_QUANTIDADE_PRODUTOS AS 
SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL 
FROM ITENS_NOTAS_FISCAIS  INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO;

SELECT * FROM VW_QUANTIDADE_PRODUTOS
WHERE QUANTIDADE_TOTAL > 394000 
ORDER BY QUANTIDADE_TOTAL DESC;
