-- AGRUPAR RESULTADOS DE SAIDA

/*
Para usar GROUP BY é necessário que haja na seleção pelo 
menos 1 campo onde é aplicada uma FUNÇÃO DE AGREGAÇÃO.
FUNÇÕES DE AGRAGAÇÃO: SUM(),AVG(), MAX(), MIN(), COUNT().
*/

SELECT * FROM ITENS_NOTAS_FISCAIS ORDER BY CODIGO_DO_PRODUTO;

SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) AS TOTAL_DE_VENDAS
FROM ITENS_NOTAS_FISCAIS 
--WHERE CODIGO_DO_PRODUTO = '1101035' AND QUANTIDADE = 99
GROUP BY CODIGO_DO_PRODUTO
HAVING SUM(QUANTIDADE) > 394000
ORDER BY TOTAL_DE_VENDAS DESC;

SELECT CIDADE, AVG(IDADE) AS [IDADE MEDIA], SUM(LIMITE_DE_CREDITO) AS CREDITO FROM TABELA_DE_CLIENTES GROUP BY CIDADE;

-- CONTAR NUMERO DE CLIENTES DE UMA CIDADE

SELECT CIDADE, COUNT(*) AS [NUMERO DE CLIENTES] FROM TABELA_DE_CLIENTES GROUP BY CIDADE;

SELECT EMBALAGEM, COUNT(*) AS [QUANTIDADE_PRODUTO] FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'LARANJA'
GROUP BY EMBALAGEM;

-- COMANDO HAVING ENVOLVENDO AGREGAÇÃO

SELECT DISTINCT(ESTADO) FROM TABELA_DE_CLIENTES;

SELECT ESTADO, COUNT(*) AS CLIENTES 
FROM TABELA_DE_CLIENTES
WHERE IDADE > 25
GROUP BY ESTADO;

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS CREDITO 
FROM TABELA_DE_CLIENTES
GROUP BY ESTADO;
HAVING SUM(LIMITE_DE_CREDITO) >= 900000; -- CONDIÇÃO PARA AGREGAÇÃO

-- MAIOR E MENOR PREÇO POR EMABALAGEM

SELECT * FROM TABELA_DE_PRODUTOS;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS PRECO_MAX, MIN(PRECO_DE_LISTA) AS PRECO_MIN
FROM TABELA_DE_PRODUTOS
WHERE PRECO_DE_LISTA >=10
GROUP BY EMBALAGEM
HAVING MAX(PRECO_DE_LISTA) >= 20;

-- CLASSIFICANDO CAMPOS COM TESTES LÓGICOS

SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA FROM TABELA_DE_PRODUTOS;

SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA, 
(CASE WHEN PRECO_DE_LISTA>12 THEN 'CARO'
      WHEN PRECO_DE_LISTA>=7 AND PRECO_DE_LISTA<12 THEN 'EM CONTA'
	  ELSE 'BARATO' END) AS CLASSIFICACAO -- ALIAS
FROM TABELA_DE_PRODUTOS
-- WHERE SABOR='MANGA'
ORDER BY CLASSIFICACAO;

-- AGRUPAR 

SELECT 
(CASE WHEN PRECO_DE_LISTA>12 THEN 'CARO'
      WHEN PRECO_DE_LISTA>=7 AND PRECO_DE_LISTA<12 THEN 'EM CONTA'
	  ELSE 'BARATO' END) AS CLASSIFICACAO, -- ALIAS
	  COUNT(*) AS NUMERO_DE_PRODUTOS
FROM TABELA_DE_PRODUTOS
GROUP BY -- NÃO POSSO USAR ALIAS
(CASE WHEN PRECO_DE_LISTA>12 THEN 'CARO'
      WHEN PRECO_DE_LISTA>=7 AND PRECO_DE_LISTA<12 THEN 'EM CONTA'
	  ELSE 'BARATO' END);

-- DESAFIO: CLASSIFICAR CLIENTES POR LIMITE DE CREDITO

SELECT NOME, 
(CASE WHEN LIMITE_DE_CREDITO >= 150000 THEN 'CLIENTE GRANDE'
      WHEN LIMITE_DE_CREDITO >= 110000 AND LIMITE_DE_CREDITO < 150000 THEN 'CLIENTE MEDIO'
	  ELSE 'CLIENTE PEQUENO' END) AS CLASSIFICACAO
FROM TABELA_DE_CLIENTES;
