-- SUBQUERY NO COMANDO IN

SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;

SELECT * FROM TABELA_DE_CLIENTES 
WHERE BAIRRO IN(SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES);

-- DESAFIO: BUSCAR SABORES MAIS VENDIDOS

SELECT INF.CODIGO_DO_PRODUTO FROM ITENS_NOTAS_FISCAIS INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO HAVING SUM(INF.QUANTIDADE) > 394000 
ORDER BY SUM(INF.QUANTIDADE) DESC;

SELECT DISTINCT SABOR
FROM TABELA_DE_PRODUTOS 
WHERE CODIGO_DO_PRODUTO IN (
SELECT INF.CODIGO_DO_PRODUTO FROM ITENS_NOTAS_FISCAIS INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO HAVING SUM(INF.QUANTIDADE) > 394000 
);

-- SUBQUERY NO HAVING: USAR COMO FILTRO O RESULTADO DE UMA AGREGAÇÃO

-- USANDO HAVING 

SELECT EMBALAGEM, AVG(PRECO_DE_LISTA) AS PRECO_MEDIO 
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM
HAVING AVG(PRECO_DE_LISTA) <= 10; 

-- USANDO SUBQUERY 

SELECT MEDIA_EMBALAGENS.EMBALAGEM, MEDIA_EMBALAGENS.PRECO_MEDIO
FROM (
	SELECT EMBALAGEM, AVG(PRECO_DE_LISTA) AS PRECO_MEDIO 
	FROM TABELA_DE_PRODUTOS
	GROUP BY EMBALAGEM) MEDIA_EMBALAGENS
WHERE PRECO_MEDIO <= 10;
