SELECT * FROM [TABELA DE PRODUTOS];

SELECT * FROM [TABELA DE CLIENTES];

-- FILTRAR COLUNAS

SELECT [NOME],[ESTADO] 
FROM [TABELA DE CLIENTES]
ORDER BY [NOME];

SELECT [NOME] AS [NOME DO CLIENTE],[CPF],[ESTADO] AS [UF]
FROM [TABELA DE CLIENTES];

SELECT [MATRICULA] AS [IDENTIFICADOR], [VENDEDOR] AS [NOME DO VENDEDOR] 
FROM [TABELA DE VENDEDORES];

-- LISTAR VALORES DISTINTOS

SELECT DISTINCT [EMBALAGEM] FROM [TABELA DE PRODUTOS]
ORDER BY [EMBALAGEM];

-- FILTRAR LINHAS COM CONDIÇÃO

SELECT [NOME] AS [NOME DO CLIENTE],[ESTADO] AS [UF], [PRIMEIRA COMPRA]  
FROM [TABELA DE CLIENTES]
WHERE [PRIMEIRA COMPRA] = 1;

SELECT * FROM [TABELA DE PRODUTOS]
WHERE [PRECO DE LISTA] < 7.00;

SELECT * FROM [TABELA DE PRODUTOS]
WHERE [EMBALAGEM] > 'LATA'; -- ORDENAÇÃO ALFABETICA (ASCII)

SELECT [NOME],[DATA DE NASCIMENTO] FROM [TABELA DE CLIENTES]
WHERE [DATA DE NASCIMENTO] > '1995-12-31';

SELECT [NOME],[DATA DE NASCIMENTO] FROM [TABELA DE CLIENTES]
WHERE YEAR([DATA DE NASCIMENTO]) > '1995'; -- FUNÇÃO QUE EXTRAI O ANO

SELECT [NOME],[BAIRRO] FROM [TABELA DE CLIENTES]
WHERE [BAIRRO] = 'Copacabana' OR [BAIRRO] = 'Tijuca';

SELECT [NOME], [ESTADO],[PRIMEIRA COMPRA] 
FROM [TABELA DE CLIENTES]
WHERE [ESTADO] = 'SP' AND [PRIMEIRA COMPRA] = 1;

-- DESAFIO: INFORMAÇÕES ESPECIFICAS

SELECT * FROM [TABELA DE VENDEDORES];

SELECT [VENDEDOR], [PERCENTUAL COMISSAO]
FROM [TABELA DE VENDEDORES]
WHERE [PERCENTUAL COMISSAO] <= 0.08;


