SELECT COUNT(*) FROM [TABELA_DE_CLIENTES];
SELECT COUNT(*) FROM [TABELA_DE_PRODUTOS];
SELECT COUNT(*) FROM [TABELA_DE_VENDEDORES];
SELECT COUNT(*) FROM [NOTAS_FISCAIS];
SELECT COUNT(*) FROM [ITENS_NOTAS_FISCAIS];

SELECT [NOME],[CPF],[BAIRRO],[CIDADE] FROM [TABELA_DE_CLIENTES];

-- ALIAS: APELIDO PARA O CAMPO

SELECT [CPF] AS 'IDENTIFICADOR', [NOME] AS [NOME DO CLIENTE] FROM [TABELA_DE_CLIENTES] TDC;

SELECT TDC.CPF, TDC.NOME, TDC.BAIRRO FROM TABELA_DE_CLIENTES TDC;


