-- JUNTANDO TABELAS

SELECT * FROM TABELA_DE_VENDEDORES;

SELECT * FROM NOTAS_FISCAIS; -- MATRÍCULA É FK

SELECT NF.MATRICULA, V.NOME, COUNT(*) AS QUANTIDADE_NOTAS 
FROM NOTAS_FISCAIS NF
INNER JOIN TABELA_DE_VENDEDORES V
ON NF.MATRICULA = V.MATRICULA -- CAMPO EM COMUM
GROUP BY NF.MATRICULA, V.NOME;

-- DESAFIO

SELECT * FROM TABELA_DE_PRODUTOS;

SELECT * FROM ITENS_NOTAS_FISCAIS;

SELECT NF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, SUM(NF.QUANTIDADE) AS QUANTIDADE 
FROM ITENS_NOTAS_FISCAIS NF
INNER JOIN TABELA_DE_PRODUTOS TP
ON NF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY NF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO -- PRECISO USAR OS 2 CAMPOS
HAVING SUM(NF.QUANTIDADE) > 394000 
ORDER BY SUM(NF.QUANTIDADE) DESC;

-- OUTROS TIPOS DE JOIN

SELECT COUNT(*) AS TOTAL_DE_CLIENTES FROM TABELA_DE_CLIENTES;

SELECT DISTINCT -- RESULTADOS DISTINTOS
	TC.CPF AS CPF_DO_CLIENTE, 
	TC.NOME AS NOME_DO_CLIENTE, 
	NF.CPF AS CPF_DA_NOTA
FROM 
	TABELA_DE_CLIENTES TC
INNER JOIN 
	NOTAS_FISCAIS NF
ON 
	TC.CPF = NF.CPF;

-- INCLUIR CLIENTE

INSERT INTO TABELA_DE_CLIENTES 
(CPF, NOME, ENDERECO_1, ENDERECO_2,
BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO, IDADE, GENERO,
LIMITE_DE_CREDITO, VOLUME_DE_COMPRA, PRIMEIRA_COMPRA)
VALUES ('23412632331', 'Juliana Silva', 'Rua Tramandaí', ' ', 'Bangu', 'Rio de
Janeiro', 'RJ', '23400000', '1989-02-04', 33, 'F', '180000', '24500', 0);

-- ENCONTRAR CLIENTE QUE NAO FEZ VENDAS

SELECT DISTINCT -- RESULTADOS DISTINTOS
	TC.CPF AS CPF_DO_CLIENTE, 
	TC.NOME AS NOME_DO_CLIENTE 
--	,NF.CPF AS CPF_DA_NOTA
FROM 
	TABELA_DE_CLIENTES TC
LEFT JOIN -- TABELA "A ESQUERDA" (PRIMEIRA)
	NOTAS_FISCAIS NF
ON 
	TC.CPF = NF.CPF
WHERE NF.CPF IS NULL;

-- PRATICAR OUTROS JOINS

SELECT COUNT(*) FROM TABELA_DE_CLIENTES; -- 16 CLIENTES

SELECT COUNT(*) FROM TABELA_DE_VENDEDORES; -- 4 VENDEDORES

-- COMPARAR BAIRRO DO CLIENTE COM BAIRRO DO VENDEDOR

SELECT DISTINCT
TV.NOME AS NOME_DO_VENDEDOR
,TV.BAIRRO AS BAIRRO_DO_VENDEDOR
,TC.BAIRRO AS BAIRRO_DO_CLIENTE
,TC.NOME AS NOME_DO_CLIENTE
FROM
	TABELA_DE_CLIENTES TC
RIGHT JOIN
	TABELA_DE_VENDEDORES TV
ON TC.BAIRRO = TV.BAIRRO
WHERE TC.NOME IS NULL;

-- 7 CLIENTES POSSUEM VENDEDORES NO SEU BAIRRO
-- 3 VENDEDORES POSSUEM CLIENTES NO SEU BAIRRO
-- ROBERTA MARTINS COPACABANA NAO POSSUI CLIENTE EM SEU BAIRRO

-- CLIENTES QUE NAO POSSUEM VENDEDORES EM SEU BAIRRO 

SELECT DISTINCT
TV.NOME AS NOME_DO_VENDEDOR
,TV.BAIRRO AS BAIRRO_DO_VENDEDOR
,TC.BAIRRO AS BAIRRO_DO_CLIENTE
,TC.NOME AS NOME_DO_CLIENTE
FROM
	TABELA_DE_CLIENTES TC
LEFT JOIN
	TABELA_DE_VENDEDORES TV
ON TC.BAIRRO = TV.BAIRRO
WHERE TV.NOME IS NULL;

-- 9 CLIENTES NAO POSSUEM VENDEDOR EM SEU BAIRRO

-- DUAS RESPOSTAS EM UMA UNICA CONSULTA

SELECT DISTINCT
TV.NOME AS NOME_DO_VENDEDOR
,TV.BAIRRO AS BAIRRO_DO_VENDEDOR
,TC.BAIRRO AS BAIRRO_DO_CLIENTE
,TC.NOME AS NOME_DO_CLIENTE
FROM
	TABELA_DE_CLIENTES TC
FULL JOIN
	TABELA_DE_VENDEDORES TV
ON TC.BAIRRO = TV.BAIRRO;
