-- COMANDO UPDATE 

-- APLICAR 10% DE DESCONTO EM LATAS

SELECT * FROM [TABELA DE PRODUTOS]
WHERE [EMBALAGEM] = 'LATA';

UPDATE [TABELA DE PRODUTOS]
SET [PRECO DE LISTA] = [PRECO DE LISTA] * 0.9
WHERE [EMBALAGEM] = 'LATA';

-- ALTERAR PREÇO E TIPO DE EMBALAGEM

SELECT * FROM [TABELA DE PRODUTOS]
WHERE [CODIGO DO PRODUTO] = '1088126';

UPDATE [TABELA DE PRODUTOS]
SET [EMBALAGEM] = 'GARRAFA', [PRECO DE LISTA] = 8.10
WHERE [CODIGO DO PRODUTO] = '1088126';

-- DELETAR PRODUTO

DELETE FROM [TABELA DE PRODUTOS]
WHERE [CODIGO DO PRODUTO] = '1004327';
