-- PRATICA DE EXPRESSÕES LÓGICAS

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR='MANGA' AND TAMANHO='470 ML';
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR='MANGA' OR TAMANHO='470 ML';
SELECT * FROM TABELA_DE_PRODUTOS WHERE NOT(SABOR='MANGA' AND TAMANHO='470 ML');
SELECT * FROM TABELA_DE_PRODUTOS WHERE NOT(SABOR='MANGA' OR TAMANHO='470 ML');

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR IN('MANGA','LARANJA','MELANCIA') AND TAMANHO= '1 Litro';

SELECT * FROM TABELA_DE_CLIENTES WHERE CIDADE IN('RIO DE JANEIRO','SAO PAULO') AND (IDADE >= 20 AND IDADE <= 25);
SELECT * FROM TABELA_DE_CLIENTES WHERE CIDADE IN('RIO DE JANEIRO','SAO PAULO') AND (IDADE BETWEEN 20 AND 25);

-- COMANDO LIKE

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR IN('LIMA/LIMAO','MORANGO/LIMAO');

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE '%LIMAO';
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE '%MACA%';
SELECT * FROM TABELA_DE_PRODUTOS WHERE (SABOR LIKE 'MORANGO%') AND (EMBALAGEM = 'PET');

SELECT * FROM TABELA_DE_CLIENTES WHERE NOME LIKE '%SILVA%';

-- CLAUSULA DISTINCT

SELECT DISTINCT(EMBALAGEM) FROM TABELA_DE_PRODUTOS WHERE SABOR='MACA';
SELECT DISTINCT(SABOR) FROM TABELA_DE_PRODUTOS;

-- LIMITAR SAIDA

SELECT TOP 5 * FROM TABELA_DE_CLIENTES;

-- ORDENAR SAIDA

SELECT TOP 5 * FROM TABELA_DE_PRODUTOS ORDER BY PRECO_DE_LISTA DESC;
SELECT * FROM TABELA_DE_PRODUTOS ORDER BY NOME_DO_PRODUTO;
SELECT * FROM TABELA_DE_PRODUTOS ORDER BY EMBALAGEM DESC,NOME_DO_PRODUTO DESC;

-- DESAFIO: Qual foi a maior venda do produto "Linha Refrescante - 1 Litro - Morango/Limao" em quantidade?

-- 1) BUSCAR CÓDIGO DO PRODUTO

SELECT * FROM TABELA_DE_PRODUTOS WHERE NOME_DO_PRODUTO = 'Linha Refrescante - 1 Litro - Morango/Limao'; --1101035

-- 2) BUSCAR CÓDIGO NA TABELA DE NOTAS FISCAIS (ORDERNAR EM ORDEM DECRESCENTE)
SELECT * FROM ITENS_NOTAS_FISCAIS
WHERE CODIGO_DO_PRODUTO = '1101035'
ORDER BY QUANTIDADE DESC;
