-- FUNÇÕES

/*
Vai aplicar para cada linha uma função e exibir 
no resultado da consulta o resultado da função.
Tipos: Strings (textos), Datas, Matemáticas, Conversão de dados, outras.
Não é padronizado. Cada banco de dados tem suas próprias funções.
*/

-- FUNÇÕES DE TEXTO

SELECT * FROM TABELA_DE_CLIENTES;

SELECT 
	NOME, 
	LOWER(NOME) AS NOME_MINUSCULO, 
	UPPER(NOME) AS NOME_MAIUSCULO
FROM 
	TABELA_DE_CLIENTES;

SELECT 
	NOME, 
	CONCAT(ENDERECO_1,', ',BAIRRO,', ', CIDADE,'/',ESTADO,' - ', CEP) AS ENDERECO_COMPLETO
FROM
	TABELA_DE_CLIENTES;

SELECT * FROM TABELA_DE_PRODUTOS;

SELECT 
	NOME_DO_PRODUTO, 
	LEFT(NOME_DO_PRODUTO,3) AS TRES_PRIMEIROS_CARACTERES
FROM 
	TABELA_DE_PRODUTOS;

-- SUBSTITUIR LITRO/LITROS POR L

SELECT 
	TAMANHO,
	REPLACE(
		(REPLACE(TAMANHO,'Litros','L')),'Litro','L'
		) AS TAMANHO_MODIFICADO
FROM
	TABELA_DE_PRODUTOS;

-- DESAFIO: CHARINDEX

SELECT NOME, CHARINDEX(' ',NOME,1) FROM TABELA_DE_CLIENTES;

SELECT 
	NOME, 
	SUBSTRING(NOME, 1, CHARINDEX(' ',NOME,1))
FROM 
	TABELA_DE_CLIENTES;

-- FUNÇÕES DE DATA E HORA

SELECT 
	GETDATE() AS DATA_HOJE -- DATA E HORA ATUAL 
	,DATEADD(DAY,10,GETDATE()) AS DATA_DAQUI_10_DIAS
	,DATEDIFF(DAY,'2022-01-01',GETDATE()) AS DIAS_DESDE_DATA
	,DATEDIFF(MONTH,'2022-01-01',GETDATE()) AS MESES_DESDE_DATA	
	,DATEPART(DAY,GETDATE()) AS DIA_HOJE	
	;

SELECT ISDATE('2020-01-01'); -- TRUE OR FALSE

SELECT ISDATE(DATETIMEFROMPARTS(2020,02,28,00,00,00,00));

-- DESAFIO: DATENAME

SELECT 
	NOME + ', ' +
	+ DATENAME(WEEKDAY,DATA_DE_NASCIMENTO) + ' , '
	+ DATENAME(DAY,DATA_DE_NASCIMENTO) + ' de '
	+ DATENAME(MONTH,DATA_DE_NASCIMENTO) + ' de '
	+ DATENAME(YEAR,DATA_DE_NASCIMENTO) AS DATA_EXTENSO
FROM
	TABELA_DE_CLIENTES;

-- FUNÇÕES NUMÉRICAS

SELECT 
	ROUND(3.437,2) AS DUAS_CASAS_DECIMAIS -- 3.440
	,CEILING(3.433) AS MAIOR_INTEIRO -- 4
	,FLOOR(3.433) AS MENOR_INTEIRO -- 3
	,POWER(12,4) AS POTENCIA -- LIMITE DE SAIDA
	,EXP(3) AS EXPONENCIAL -- e^3
	,SQRT(300) AS RAIZ_QUADRADA -- 17,32
	,ABS(-10) AS ABSOLUTO -- 10
; 

-- DESAFIO: Calcule o valor do imposto pago no ano de 2016, arredondando para o menor inteiro.

SELECT * FROM NOTAS_FISCAIS;

SELECT 
	YEAR(DATA_VENDA) AS ANO_VENDA
	,FLOOR(
		SUM(
			IMPOSTO * (QUANTIDADE * PRECO)
		)
	) AS SOMA_IMPOSTO
FROM 
	NOTAS_FISCAIS NF
INNER JOIN 
	ITENS_NOTAS_FISCAIS INF
ON 
	NF.NUMERO = INF.NUMERO
WHERE
	(YEAR(DATA_VENDA)) = 2016
GROUP BY 
	YEAR(DATA_VENDA);

